
path: /home/jackplum/Documents/projects/voidspotter/roboflowV13_yolov8 # dataset root dir
train: train/images # train images (relative to 'path')
val: valid/images # val images (relative to 'path')

# Classes
names:
  0: good_void